name: hugo gh-pages

on:
  push:
    branches:
      - source # default branch for template source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master # Deploy branch
#           force_orphan: true
#           cname: datacommons.org.nz
          user_name: 'PardusEidolon'
          user_email: '38515818+PardusEidolon@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
